apiVersion: v1
kind: ServiceAccount
metadata:
  name: temple-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "temple.backend.labels" . | nindent 4 }}
automountServiceAccountToken: false
