apiVersion: v1
kind: ServiceAccount
metadata:
  name: temple-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "temple.frontend.labels" . | nindent 4 }}
automountServiceAccountToken: false
